version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: byte-cloud-db
    environment:
      POSTGRES_DB: byte_cloud
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
